#!/usr/bin/env bash
# Regenerate config/fragments/cachy-extras.conf from the linux-cachyos config.
# Adopts y/m symbols absent from Ubuntu's base config and not set by another
# fragment. Run after a CACHY_TAG bump and review the diff.
#
# It also reports, without adopting, symbols Ubuntu sets to `n` that CachyOS
# enables. Those are not additions but disagreements, and they cannot be taken
# automatically: some are the Ubuntu adaptations this project exists to keep.
# They were invisible here until an audit found 24 policy symbols being dropped
# silently, so they are printed for a human to rule on and recorded in
# config/parity-review.txt.
. "$(dirname "$0")/lib.sh"

REF="$ROOT/config/base/cachyos-reference.config"
OUT="$ROOT/config/fragments/cachy-extras.conf"
URL=${CACHY_CONFIG_URL:-https://raw.githubusercontent.com/CachyOS/linux-cachyos/master/linux-cachyos/config}

say "fetching reference config"
curl -fL --retry 3 -o "$REF" "$URL"

python3 - "$ROOT" "$REF" "$OUT" <<'PY'
import re, sys, pathlib

root, ref, out = map(pathlib.Path, sys.argv[1:4])

def parse(path):
    vals = {}
    for line in path.read_text().splitlines():
        m = re.match(r'^(CONFIG_\w+)=(.*)$', line)
        if m:
            vals[m.group(1)] = m.group(2)
        elif m := re.match(r'^# (CONFIG_\w+) is not set$', line):
            vals[m.group(1)] = 'n'
    return vals

base = parse(root / 'config' / 'base' / 'ubuntu-26.04-amd64.config')
cachy = parse(ref)

# Symbols the hand-written fragments own.
owned = set()
for frag in (root / 'config' / 'fragments').glob('*.conf'):
    if frag.name == 'cachy-extras.conf':
        continue
    for tok in re.findall(r'\b([A-Z0-9_]{3,})\b', frag.read_text()):
        owned.add('CONFIG_' + tok)

skip = re.compile(r'_(DEBUG|TEST|TORTURE|SANITY)\b|^CONFIG_(DEBUG|TEST)_|_(RISCV|ARM|ARM64|MIPS|POWERPC|LOONGARCH)\d*$')

picked, disagreements = [], []
for sym, val in sorted(cachy.items()):
    if val not in ('y', 'm') or sym in owned or skip.search(sym):
        continue
    if sym not in base:
        picked.append((sym, val))
    elif base[sym] == 'n':
        # Ubuntu turned it off, CachyOS turned it on. Never adopted here.
        disagreements.append((sym, val))

lines = [
    '# Generated by scripts/gen-cachy-extras.sh — do not edit by hand.',
    '#',
    '# Drivers enabled by linux-cachyos that Ubuntu\'s base config predates.',
    '# Regenerate after a CACHY_TAG bump and review the diff.',
    '',
]
lines += [f'{"-e" if v == "y" else "-m"} {s.removeprefix("CONFIG_")}' for s, v in picked]
out.write_text('\n'.join(lines) + '\n')
print(f'>> wrote {out.relative_to(root)}: {len(picked)} symbols')

# Not adopted, only reported. Driver debug noise is filtered out so the list
# stays short enough to actually read.
noise = re.compile(r'(^|_)(DEBUG|DEBUGFS|TRACE|TRACER|TRACING|SELFTEST|TEST|STAT|STATS|'
                   r'VERBOSE|SANITY|TORTURE|FAULT_INJECTION|ERROR_INJECTION|MOCKUP|DUMMY)(_|$)')
review = [(s, v) for s, v in disagreements if not noise.search(s)]
report = root / 'config' / 'parity-review.txt'
report.write_text(
    '# Symbols Ubuntu disables and CachyOS enables, excluding debug options.\n'
    '# Not adopted automatically. Decide each one: add to cachy.conf to match\n'
    '# upstream, or leave it if Ubuntu\'s choice is deliberate.\n#\n'
    + '\n'.join(f'{"-e" if v == "y" else "-m"} {s.removeprefix("CONFIG_")}'
                 for s, v in review) + '\n')
print(f'>> wrote {report.relative_to(root)}: {len(review)} disagreements to review '
      f'({len(disagreements) - len(review)} debug symbols filtered)')
if review:
    print('>> review that file before releasing; anything already handled in')
    print('>> cachy.conf will show as owned and not appear there')
PY
